name: Naev Infrastructure Deployment
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  "Create_Release":
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

  "Build_Publish_Images":
    needs: Create_Release
    strategy:
      fail-fast: true
      matrix:
        include:
          - context: "naev-linux-archaic"
            arch: amd64
            imagename: "naev-linux-archaic"
          - context: "naev-docs"
            arch: amd64
            imagename: "naev-docs"
          - context: "naev-linux-lts"
            arch: amd64
            imagename: "naev-linux-lts"
          - context: "naev-linux-latest"
            arch: amd64
            imagename: "naev-linux-latest"
          - context: "naev-release"
            arch: amd64
            imagename: "naev-release"
          - context: "naev-steamruntime"
            arch: amd64
            imagename: "naev-steamruntime"
          - context: "naev-windows"
            arch: amd64
            imagename: "naev-windows"
          - context: "naev-macos"
            arch: amd64
            imagename: "naev-macos"
          - context: "naev-macos"
            arch: aarch64
            imagename: "naev-macos"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Docker meta (amd64 versions)
        id: docker_meta_amd64
        if: ${{ matrix.arch == 'amd64' }}
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: ghcr.io/naev/${{ matrix.imagename }}

      - name: Docker meta (aarch64 versions)
        id: docker_meta_aarch64
        if: ${{ matrix.arch == 'aarch64' }}
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: ghcr.io/naev/${{ matrix.imagename }}
          flavor: |
            suffix=-${{ matrix.arch }},onlatest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build_amd64
        if: ${{ matrix.arch == 'amd64' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: "${{ matrix.context }}/Dockerfile.${{ matrix.arch }}"
          push: true
          tags: ${{ steps.docker_meta_amd64.outputs.tags }}

      - name: Build and push
        id: docker_build_aarch64
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: "${{ matrix.context }}/Dockerfile.${{ matrix.arch }}"
          push: true
          tags: ${{ steps.docker_meta_aarch64.outputs.tags }}
