name: Naev Infrastructure Deployment
on:
  push:
    tags:
      - "v*.*.*"
permissions: {}

jobs:
  deploy_images:
    permissions:
      contents: write
    uses: naev/naev-infrastructure/.github/workflows/docker_build.yml@main
    with:
      publish: true
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: deploy_images
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        allowUpdates: true
