name: Naev Infrastructure Weekly Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"
permissions: {}

jobs:
  update_tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Update 'weekly' tag
      uses: EndBug/latest-tag@latest
      with:
        ref: weekly
  deploy_images:
    permissions:
      contents: write
      packages: write
    needs: update_tag
    uses: naev/naev-infrastructure/.github/workflows/docker_build.yml@main
    with:
      publish: true
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: deploy_images
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allowUpdates: true
        name: Weekly Build
        tag: weekly
