name: Build Docker Image
on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
permissions: {}

jobs:
  image_build:
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: "naev-artwork/blender2.79b"
            imagename: "naev-artwork"
            blender: "blender2.79b"
          - context: "naev-docs"
            imagename: "naev-docs"
          - context: "naev-release"
            imagename: "naev-release"
          - context: "naev-steamruntime"
            imagename: "naev-steamruntime"
          - context: "naev-windows"
            imagename: "naev-windows"
          - context: "naev-macos"
            imagename: "naev-macos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate image metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/naev/${{ matrix.imagename }}
          flavor: |
            latest=${{ inputs.publish }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: "${{ matrix.context }}/Dockerfile"
          push: ${{ inputs.publish }}
          tags: ${{ steps.docker_meta.outputs.tags }}
