name: Naev Infrastructure Testing
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_images:
    uses: naev/naev-infrastructure/.github/workflows/docker_build.yml@main
    with:
      publish: false