name: Naev Infrastructure Testing
on: [push, pull_request]

jobs:
  "Build_Test_Images":
    strategy:
      fail-fast: true
      matrix:
        include:
          - context: "naev-linux-archaic"
            file: Dockerfile.amd64
            imagename: "naev-linux-archaic"
          - context: "naev-docs"
            file: Dockerfile.amd64
            imagename: "naev-docs"
          - context: "naev-linux-lts"
            file: Dockerfile.amd64
            imagename: "naev-linux-lts"
          - context: "naev-linux-latest"
            file: Dockerfile.amd64
            imagename: "naev-linux-latest"
          - context: "naev-release"
            file: Dockerfile.amd64
            imagename: "naev-release"
          - context: "naev-steamruntime"
            file: Dockerfile.amd64
            imagename: "naev-steamruntime"
          - context: "naev-windows"
            file: Dockerfile.amd64
            imagename: "naev-windows"
          - context: "naev-macos"
            file: Dockerfile.amd64
            imagename: "naev-macos"
          - context: "naev-macos"
            file: Dockerfile.arm64
            imagename: "naev-macos"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: ghcr.io/naev/${{ matrix.imagename }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.CR_PAT }}

      - name: Test Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.file }}
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
