name: "Build Website" 
on:
  workflow_call:
    inputs:
      publish_type:
        required: true
        type: string
jobs:
  website_publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.publish_type == 'website'
    container:
      image: "ghcr.io/naev/naev-docs:latest"
    steps:
      - name: "Checkout `naev.org`"
        uses: actions/checkout@v2
        with:
          path: /__w/naev.github.io/naev.github.io/prod
      - name: "Clone `naev-website`"
        uses: actions/checkout@v2
        with:
          repository: 'naev/naev-website'
          path: /__w/naev.github.io/naev.github.io/staging
      - name: "Build Website"
        run: make
        working-directory: ${{ github.workspace }}/staging
      - name: "Stage Updated Files"
        run: rsync -avzh output/ /__w/naev.github.io/naev.github.io/prod
        working-directory: ${{ github.workspace }}/staging
      - name: "Add Updated Files"
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add *
        working-directory: /__w/naev.github.io/naev.github.io/prod
      - name: "Commit Updated Files"
        run: |
          git commit -m "Website Updates" -a
          git pull
        working-directory: /__w/naev.github.io/naev.github.io/prod
      - name: "Push Updates to `naev.org`"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: /__w/naev.github.io/naev.github.io/prod   
  docs_publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.publish_type == 'docs'
    container:
      image: "ghcr.io/naev/naev-docs:latest"
    steps:
      - name: "Checkout `naev.org`"
        uses: actions/checkout@v2
        with:
          path: /__w/naev.github.io/naev.github.io/prod
      - name: "Checkout `naev`"
        uses: actions/checkout@v2
        with:
          repository: 'naev/naev'
          path: /__w/naev.github.io/naev.github.io/staging
      - name: "Build API Docs"
        run: |
          meson setup build . -Dexecutable=disabled
          meson compile -C build
        working-directory: ${{ github.workspace }}/staging
      - name: "Build Manual PDF"
        run: |
          make naev_dev_manual.pdf
        working-directory: ${{ github.workspace }}/staging/docs/manual
      - name: "Stage Updated Files"
        run: 
          rsync -avzh build/docs/lua/ /__w/naev.github.io/naev.github.io/prod/api
          rsync -avzh docs/manual/naev_dev_manual.pdf /__w/naev.github.io/naev.github.io/prod/devmanual
        working-directory: ${{ github.workspace }}/staging
      - name: "Add Updated Files"
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add *
        working-directory: /__w/naev.github.io/naev.github.io/prod
      - name: "Commit Updated Files"
        run: |
          git commit -m "Documentation Updates" -a
          git pull
        working-directory: /__w/naev.github.io/naev.github.io/prod
      - name: "Push Updates to `naev.org`"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: /__w/naev.github.io/naev.github.io/prod
